sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - cmake-data
      - g++-7
      - libgtest-dev
      - valgrind


before_install:
  - export CXX="g++-7"
  - export CC="gcc-7"
  - git clone https://github.com/Grauniad/CMakeUtils.git
  - g++-7 --version

install:
  - pip install --user cpp-coveralls
  - ./buildDeps.sh
  
script: 
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cd ..
  - ./CMakeUtils/travis/doCoverage.sh -e src/benchmark.cpp
